n = input('Digite algo: ')
print('Isso é numérico?')
print(n.isnumeric())
print('Isso é decimal?')
print(n.isdecimal())
print('Isso é um título?')
print(n.istitle())
print('Isso é um alpha?')
print(n.isalpha())
print('Isso é um alpha numérico?')
print(n.isalnum())
print('Isso é um espaço?')
print(n.isspace())
print('Isso é um dígito?')
print(n.isdigit())
print('Isso é imprimível?')
print(n.isprintable())
print('Isso é um caractere do tipo 7-bit US-ASCII?')
print(n.isascii())
print('Isso pode ser uma letra minúscula?')
print(n.islower())
print('Isso pode ser uma letra maiúscula?')
print(n.isupper())
